name: gptalk
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2

  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

  flutter_spinkit: ^5.1.0
  flutter_tts: ^3.6.3
  freezed_annotation: ^2.2.0

  hooks_riverpod: ^2.3.6

  http: ^0.13.5
  intl: ^0.18.1

  json_annotation: ^4.7.0
  speech_to_text: ^6.1.1

dev_dependencies:

  build_runner: ^2.3.2

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/

flutter_native_splash:
  image: "assets/images/ic_launcher.png"
  color: "2e2e2e"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

adaptive_icon_background: "#ff0000"
adaptive_icon_foreground: "assets/images/ic_launcher.png"
